### ISSUE TITLE
Error "Unknown directive" on example GraphCool project

### ISSUE THREAD

**Issue by lucfranken** [apollographql/apollo-codegen#118]
I get an error when I take a new standard GraphCool (@graphcool) project.

See command line input below: (This API url actually works so you can test it as this is the best reproduction

```bash
$ apollo-codegen introspect-schema https://api.graph.cool/simple/v1/cj2ughqytctr20169wr8ag4tv --output schema.json
$ apollo-codegen generate **/*.graphql --schema schema.json --target flow --output schema.flow.js
Unknown directive "isUnique".
Unknown directive "relation".
```

Is there a reason why those directives (which seem custom for GraphCool) are parsed? Or can we supply them manually to apollo-codegen?

I tried this apollo-codegen based on: 
https://apollographql.slack.com/archives/C0Z9ZBDF0/p1495109654174839

**Comment by martijnwalraven** [comment]
The `Unknown directive` message comes from `graphql-js`, not from `apollo-codegen`. This is due to a built-in validation rule that checks whether a directive is valid for a particular schema and AST location, see [here](https://github.com/graphql/graphql-js/blob/89f3f1a319bb913616f2910e8a806170155ffaf0/src/validation/rules/KnownDirectives.js). 

Custom directives will have to be included in the schema, and they don't seem to be part of the introspection query result you get from the Graphcool endpoint. Maybe you could post on the Graphcool Slack to ask about this, and point them to this issue?

**Comment by lucfranken** [comment]
Thanks @martijn ! Informed Nilan already!

**Comment by rricard** [comment]
Seems to be handled on graphcool/console. Closing the issue

**Comment by lucfranken** [comment]
@rricard  Correct, it works now!
