### ISSUE TITLE
Generate TypeScript interfaces from .graphqls (schema)

### ISSUE THREAD

**Issue by kirillgroshkov** [apollographql/apollo-codegen#248]
Is it possible to generate TypeScript interfaces from .graphqls (schema definition, not query definition) files? Or from json schema? Or vice-versa - from *.d.ts to .graphqls? I'm trying to avoid duplication of interfaces in 2 languages: TS and GraphqlS.

**Comment by martijnwalraven** [comment]
The goal of apollo-codegen is precisely to avoid writing duplicate interfaces, but the starting point is GraphQL, because the schema is what defines the contract between your client and server. We don't generate interfaces from the schema directly however, because clients only select subsets of that data in queries. So only query-specific types give you true type safety by guaranteeing that the data you get matches the shape of the interfaces.

**Comment by kctang** [comment]
Thanks for the explanation @martijnwalraven. I had similar expectations when attempting to generate TypeScript definitions for my GraphQL schema.

I did spend some time trying to achieve that (generate for *.graphqls) until I came to this thread...then it make sense! :-)

It might be helpful to describe this concept of "TypeScript definition is generated based on (each) query rather than everything the schema has to offer" in the docs as it will be helpful to new devs.
