### ISSUE TITLE
swift generated code optimiziations / snapshot additional code bloat

### ISSUE THREAD

**Issue by johndpope** [apollographql/apollo-codegen#262]
when I generate code from querymodel
apollo-codegen generate corewatchlist.graphql --schema schema.json --output API.swift

All files are here -> 
https://gist.github.com/johndpope/7cc331ad7182fb5ed112738500af5383

the resulting file is > 1MB.

I get snapshot code adding
public var snapshot: Snapshot
this happens in almost 600 occurrences
<img width="847" alt="screen shot 2017-10-03 at 12 41 20 pm" src="https://user-images.githubusercontent.com/289994/31137237-aa86f88e-a838-11e7-990b-2f216fa72bf0.png">

I'm thinking using the typed models maybe better.
Using the shopify code I get > 100 classes - but file size is tighter all up - 705KB
https://gist.github.com/wwe-johndpope/eff04d5297024f8570174a52a25e7c4f

I was thinking if the snapshot was for testing??? maybe it could be optionally added or excluded?
just a thought

**Comment by martijnwalraven** [comment]
I'm not entirely happy with the generated code either, but the snapshots are a necessary evil for allowing mutable data with type- or fragment-specific projections.

You can do something like:
```swift
hero.asDroid?.primaryFunction = "Foo"
```
or
```swift
hero.fragments.heroDetails.name = "Bla"
```
for example, and you expect that the updated values of `primaryFunction` or `name` are stored as part of `hero`. So that's why the generated code relies on a `snapshot` to store the actual values of fields, instead of using stored properties in the struct.

**Comment by johndpope** [comment]
thanks for explanation @martijnwalraven

**Comment by johndpope** [comment]
it's generally accepted that you can't / shouldn't store properties in extensions.
but if you could have the snapshot stored in the super 
Graphql / this would alleviate having all the child nodes needing this property. 
this would shed all this extra code.
      public var snapshot: Snapshot

      public init(snapshot: Snapshot) {
        self.snapshot = snapshot
      }


a while back - there was some developers who did this via objc code.

the other idea is that for each model - this extra bloat could be saved separately as an extension.
eg. 
AddToWatchlist.swift 
would contain bare stuff
AddToWatchlist+Snapshot.swift 

would contain extra code needed to do all snapshot stuff 
extension AddToWatchlist{


}
<img width="234" alt="screen shot 2017-10-04 at 10 29 46 am" src="https://user-images.githubusercontent.com/289994/31181306-f90d7990-a8ee-11e7-9366-49417bca213a.png">

**Comment by martijnwalraven** [comment]
I'm not sure I understand your proposals. The generated types are structs, so there is no superclass. And the `snapshot` is a stored property, so it can't be in an extension. All other properties are computed properties. The snapshot is no 'bloat', but a workaround to allow for consistent operations on type- or fragment projections.

**Comment by martijnwalraven** [comment]
Going to close this because it doesn't seem actionable, but feel free to reopen if you want to discuss further.

**Comment by johndpope** [comment]
For reference/ https://marcosantadev.com/stored-properties-swift-extensions


In the > 10,000 lines of code there’s something like > 500 snapshot instantiations. This objc  hack could drastically simplify this. Consider.

**Comment by martijnwalraven** [comment]
Swift structs don't use the Objective-C runtime, so associated objects are not an option. But even if it was, it probably wouldn't make sense to use it because all getters and setters need access to `snapshot`, and making it an associated object would slow that down.

I don't really see the issue here. Code duplication isn't a problem because it's all generated code.
