### ISSUE TITLE
Feature request: node api w/ option to pass in graphql inputs manually

### ISSUE THREAD

**Issue by jwickens** [apollographql/apollo-codegen#282]
Hi one of the great benefits of https://www.npmjs.com/package/gql2ts is that it provides a (documented) programable api. I have my graphql schema split into several *.graphql files and id like to pass this in and write out to a flowtypes.js file with a node.js script.

**Comment by martijnwalraven** [comment]
I think a programmatic API would be great, but your use case currently isn't a particularly good fit for `apollo-codegen`. It generates query-specific types, so you'll need queries in addition to the schema.

Do you generate types for the schema because you're using this for a server implementation?

**Comment by jwickens** [comment]
@martijnwalraven yeah you're right, ive settled on using this tool for generating client side types and  then in each of my microservices that my graphql service is exporting i define the types first there and import them to my graphql project to be type safe server side.
