### ISSUE TITLE
Exact flow types make typing react cumbersome

### ISSUE THREAD

**Issue by jfuchs** [apollographql/apollo-codegen#285]
There's a common pattern we've seen with our flow-typed components where a parent component defines a fragment that composes a child component's fragment. For example, given the following fragments (assume they have corresponding components):

```graphql
fragment UserProfile_user on User {
  username
  ...UserAvatar_user
}

fragment UserAvatar_user on User {
  imageId
}
```

This might yield these type definitions:

```javascript
export type UserProfileUserFragment = {|
  username: string,
  id: string
|}

export type UserAvatarUserFragment = {|
  id: string
|}
```

The problem comes when the parent component calls the child component:

```javascript
// Inside UserProfile:
render() {
  // ...
    <UserAvatar user={this.props.user} /> // Flow complains here
  // ...
}
```

Flow will complain because UserProfile's prop `user` has a username, so it isn't a `UserAvatarUserFragment`. The code would work as intended, but because `UserAvatarUserFragment` is an _exact_ type, the presence of a `username` breaks typing.

### Possible solutions:

- Stop using exact types (I'm not sure if that makes sense given https://github.com/apollographql/apollo-codegen/issues/62)
- Add flow typing to [graphql-anywhere](https://github.com/apollographql/graphql-anywhere)'s `filter` method. I'm not sure I like this because the behavior of filter seems like an unnecessary expense.
- I'm sure there are others, but that's all I can think of right now.

**Comment by leethree** [comment]
I'm also struggling with this issue regarding the exact types generated by apollo-codegen.

A nice solution I found is that exact types can be converted to inexact types using:
```
type InexactA = { ...A };
```

So in your example, define the props of UserAvatar as the following:
```js
type Props = {
  user: { ... UserAvatarUserFragment },
};
class UserAvatar extends React.Component<Props> {
  // ...
}
```

Full example here: https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgDk2pFdA3MkQB5Z6i4CeGIqACqAZyLYACtUgpoRMRIBi2EgHM0RAHb4AvKADeAH0ShQAV3HYtJTQC5Qo3NhRa1AGlOgUAEwdOXN0QjAF92Lhx8fkERKwBBADcSXBJsRWwVdU0dUH1jL19-Z1c1YLDEaKF0xOTU6VgMUVzDL0sJBwNQADoe6qSUtKtMjW18EM8QtkQyaBJRJr7a7FBOXG0fJuJyXC6AYRosLVGAHkWB+saAPhazRi0fCQAKAEobs1BGXHNrUC1zaGgbDMYXKlViEnqsnkFyaeVaVgc6UhcgUQ1UIx0EymMzmCysyPkKw4a3umyYO32mFgRx0p3xMhRMOuBi8dwe2Beb3en2+WlAjzpEhqAwsVl0BlwAAsUKIuhhqI0um1sCFQMBLs8gaAQYggA

**Comment by k** [comment]
We just run a script that strips out the pipes. Written by @rj254. 

https://gist.github.com/k/cfcb791b866592e946762e9a2bdf90dc

**Comment by lewisf** [comment]
This is no longer the default and now a configurable option in `flow-modern`: https://github.com/apollographql/apollo-codegen/blob/master/src/cli.js#L146-L150

Even though i'd love if everyone gave flow-modern a try to see if it fits their needs because it will soon be the default in releases, I'm willing to accept a PR to remove exact types from the older flow target since it's clearly a problem for everyone

**Comment by lewisf** [comment]
This is no longer the default and now a configurable option in `flow-modern`: https://github.com/apollographql/apollo-codegen/blob/master/src/cli.js#L146-L150

Even though i'd love if everyone gave flow-modern a try to see if it fits their needs because it will soon be the default in releases, I'm willing to accept a PR to remove exact types from the older flow target since it's clearly a problem for everyone

**Comment by lewisf** [comment]
Going to close this otherwise -- we are REALLY looking for flow-modern to be the target that we improve to support everyone's needs since it will soon be the default. If the new target doesn't suit your needs, please open up a new issue on that.
