### ISSUE TITLE
Custom scalars typed as `any` in Flow

### ISSUE THREAD

**Issue by holman** [apollographql/apollo-codegen#418]
I've been investigating how difficult it would be to start moving us towards Flow's [`strict`](https://flow.org/en/docs/strict/) mode. One of the bigger areas that we'd run into is the generated types from GraphQL, specifically around custom scalars. We have one for `DateTime`, which is just an ISO 8601-formatted string.

`apollo-codegen` switched typing of custom scalars from `string` to `any` in #80. That's a good idea generally, I think, but the `any` fails Flow's strict typing.

The initial `string`, at least in our case, makes sense, I think; we're mostly just using a custom scalar to make it easier to emit proper and consistent timestamps on the server, and then transmitting them as strings just like normal. It'd be nice to be able to fall back to a string when we can in apollo-codegen, or have some way of telling it hey, these scalars aren't *actually* a big deal, and could use the `string` typing like normal.

(At least that's my read on the situation; definitely could be wrong with the best way forward with all this!)

**Comment by mike-marcacci** [comment]
Hey @holman, I'm starting the process of switching from relay to apollo, and use custom scalars for more complex all-or-nothing types, which are serialized as arrays/objects. I think ideally we would be able to specify an arbitrary mapping of custom scalars to final types.

Otherwise, `any` is probably the correct fallback for flow.

**Comment by holman** [comment]
> I think ideally we would be able to specify an arbitrary mapping of custom scalars to final types.

:+1: that would do it for me, to be honest!

**Comment by mike-marcacci** [comment]
One update: it appears that the `flow-modern` target uses the GraphQL scalar's name as its type by default. Additionally, it appears that a [custom-scalars-prefix](https://github.com/apollographql/apollo-codegen/blob/master/src/cli.js#L137) option is supposed to let you specify something like `GraphQL_` so that you could specify `type DateTime = string` in a flow libdef. However, this appears to currently be broken, and instead causes it to use `any`.
