### ISSUE TITLE
Generating unnecessary types

### ISSUE THREAD

**Issue by amol-c** [apollographql/apollo-codegen#46]
Hi,

It seems that the `apollo-codegen` is generating an unnecessary objects off the `typeName`.

I think the typeName should define the type and not the instance name.

For example:
```
        public struct PointsLastYear: GraphQLMappable {
          public let __typename = "point"
          public let time: String?
          public let value: Double?

          public init(reader: GraphQLResultReader) throws {
            time = try reader.optionalValue(for: Field(responseName: "time"))
            value = try reader.optionalValue(for: Field(responseName: "value"))
          }
        }

        public struct Point: GraphQLMappable {
          public let __typename = "point"
          public let time: String?
          public let value: Double?

          public init(reader: GraphQLResultReader) throws {
            time = try reader.optionalValue(for: Field(responseName: "time"))
            value = try reader.optionalValue(for: Field(responseName: "value"))
          }
        }
      }
```

The `typeName` for `PointsLastYear` and `Point` is the same i.e `point`.

Based on the schema below, it does seem like we are defining the `typeName` as `point`, but the generator ends up creating an additional object of the same instance type, which deems unnecessary.
```
    {
              "type": {
                "ofType": {
                  "ofType": null,
                  "name": "point",
                  "kind": "OBJECT"
                },
                "name": null,
                "kind": "LIST"
              },
              "name": "points",
              "isDeprecated": false,
              "description": null,
              "deprecationReason": null,
              "args": []
            },
            {
              "type": {
                "ofType": {
                  "ofType": null,
                  "name": "point",
                  "kind": "OBJECT"
                },
                "name": null,
                "kind": "LIST"
              },
              "name": "pointsLastYear",
              "isDeprecated": false,
              "description": null,
              "deprecationReason": null,
              "args": []
            },
```

This is causing unnecessary abstractions and objects which are really not needed as they are of the same type.

Is this the kind of expected behavior and by design ?

Please advice.

**Comment by martijnwalraven** [comment]
This is expected behavior. The type of a GraphQL object doesn't fully determine what the generated code should look like, because that also depends on what fields get selected, on the arguments used, etc. 

We don't generate Swift types based on the type definition in the GraphQL schema, but on the selections in the query. See [this blog post](https://dev-blog.apollodata.com/mapping-graphql-types-to-swift-aa85e5693db4) for more details on this mapping.

I can see how this may seem unnecessary for a type like `point`, but remember objects can have hundreds of fields of which a particular selection set in a query only selects a small subset.

Are you sure `point` should be an object? Maybe it could be a custom scalar instead? (These are not fully supported in Apollo iOS yet, but they will be soon.)
