### ISSUE TITLE
Add flag to include warning in generated files

### ISSUE THREAD

**Issue by frankdugan3** [apollographql/apollo-codegen#57]
Many generators or config editors will include a commented warning at the top of generated files to indicate that the file should be edited directly since it was generated.

Perhaps it would be a good idea to either add a flag to insert a standard warning or an argument to specify the warning text.

**Comment by martijnwalraven** [comment]
The Swift output already included a warning? Are you talking about Flow or TypeScript output?

I don't think this needs to be a flag, we should probably always include it.

**Comment by frankdugan3** [comment]
Sorry, should have been more specific. Neither the JSON schema dump or the Typescript have warnings. Haven't tried Flow.

I agree that that a flag isn't needed, but I also like the idea of making the warning text configurable via an optional argument. That way, the warning could be configured to give hints as to what called the generator or what should be edited to change the output.

**Comment by martijnwalraven** [comment]
The Swift output includes:
```swift
//  This file was automatically generated and should not be edited.
```

I think it would make sense to add a similar comment to the Flow and TypeScript output. That seems unnecessary for the JSON schema dump, because that isn't something you would write by hand anyway (plus JSON can't contain comments).

I don't really see a need to make the text configurable. If we think it isn't clear enough, we should just change it for everyone.
