### ISSUE TITLE
External updates to Swift models

### ISSUE THREAD

**Issue by sibljon** [apollographql/apollo-codegen#58]
Is there currently a mechanism by which the Swift model structs can be mutated?

My two use cases are as follows:

1. Optimistic updates -- aka the user submits a change, and we want to update the UI before receiving the response from the server
2. A source other than the GraphQL API indicates that data returned from the GraphQL API has changed -- for example, we have `unreadCount` as a property of a GraphQL model struct `A`, but push notifications also contain an `unreadCount` and when we receive a push notification, we want to mutate the `A` struct to update it's `unreadCount`.

Currently, it appears that structs are generated with properties as constants (`let`), and the simple solution would be to change these to `var`. Would this be something that would be considered to add to the `apollo-codegen` CLI as an option?

**Comment by martijnwalraven** [comment]
These are both use cases we definitely want to support. Instead of just updating the model structs for a particular query result however, I think we want changes to be applied to the normalized cache, so we can keep consistency between queries and not overwrite local changes when you reload from cache. For optimistic updates, we would also want to roll them back automatically when the real result comes back.

The precise mechanism is something we need to work on, but it could involve some kind of mutable view (maybe a functional lens) on a model struct that acts as an interface to the store. I don't think we want model structs themselves to be mutable however, because there is great value in keeping to immutable models and one way dataflow.

**Comment by martijnwalraven** [comment]
Closing this, because the generated Swift structs are now mutable in Apollo iOS 0.6.0 (currently in beta).
