### ISSUE TITLE
Incorrect code gen of field name with multiple caps in a row

### ISSUE THREAD

**Issue by spanage** [apollographql/apollo-codegen#63]
Currently in our JSON schema we have an input_obect that contains the following field
```
{
                            "name": "deviceID",
                            "description": null,
                            "type": {
                                "kind": "SCALAR",
                                "name": "String",
                                "ofType": null
                            },
                            "defaultValue": null
}
```

In the generated swift code, however, this is becoming `deviceId` and this same capitalization is being used in the endpoint request, causing it to fail as an unrecognized field.

Generated swift looks like:
```swift
public struct addUserInput: GraphQLMapConvertible {
  public var graphQLMap: GraphQLMap

  public init(firstName: String, lastName: String, identifier: String, identifierType: String, deviceId: String? = nil, clientMutationId: String? = nil) {
    graphQLMap = ["firstName": firstName, "lastName": lastName, "identifier": identifier, "identifierType": identifierType, "deviceId": deviceId, "clientMutationId": clientMutationId]
  }
}
```

**Comment by martijnwalraven** [comment]
What version of `apollo-codegen` do you have installed? We recently (in 0.10.4) [fixed a bug](https://github.com/apollographql/apollo-codegen/commit/b39a733b4c0afe5f0bfba4cdf6dd11f233100560) where the property name instead of the field name was used in input objects. So that should at least make your request work I think.

That being said, I don't like the way we currently handle capitalization, because a name like `deviceID` should be used as is and not converted to `deviceId`. The idea was to convert field names using underscores or other conventions to camel case, but that may not be worth the trouble.

**Comment by rricard** [comment]
More or less linked to #92, also adding it to the milestone.
