### ISSUE TITLE
Crash due to GraphQLEnumType variable types not serialized correctly

### ISSUE THREAD

**Issue by xiekevin** [apollographql/apollo-codegen#85]
Currently String Enum types are not being converted to its `rawValue` before being used as a parameter. This causes a crash as Swift Enum types are not allowed in JSON serialization and the following error is thrown:

```Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (_SwiftValue)'```

Here is some relevant code demonstrating the issue:

### API.swift
```
public enum Size: String {
  case small = "small" /// A Small Size
  case large = "large" /// A Large Size
}

public final class UpdateSizeMutation: GraphQLMutation {
   ...
  public var variables: GraphQLMap? {
    return ["size": size]
  }
}
```

### GraphQLNetworkTransport

```
    func send<Operation: GraphQLOperation>(operation: Operation, completionHandler: @escaping (GraphQLResponse<Operation>?, Error?) -> Void) -> Cancellable {
        let params: [String: Any] = ["query": type(of: operation).queryDocument as Any, "variables": operation.variables as Any]
        let request = manager.request(baseURLString, method: .post, parameters: params, encoding: JSONEncoding.default, headers: headers)
        ...
        return request
    }
```

The Swift Enum is therefore included inside of the `params` variable when sending the request and causes an error when encoding to JSON.

A potential fix is to use `.rawValue` for string enum types inside of `variables` during code generation.

### Potential Fix
```
  public var variables: GraphQLMap? {
    return ["size": size.rawValue]
  }
``` 

This is a problem that can also be addressed within apollo-ios.

**Comment by martijnwalraven** [comment]
I'm not sure where the `send` implementation you quoted comes from, but it's not the one in the project!

If you look at the corresponding lines in [`HTTPNetworkTransport`](https://github.com/apollographql/apollo-ios/blob/master/Sources/HTTPNetworkTransport.swift#L74-L75), they treat the body as a `GraphQLMap` and pass it to `JSONSerializationFormat.serialize` before setting it as the `httpBody`. (`GraphQLMap` is `JSONEncodable`, so that basically just calls `jsonValue` on it to get a JSON value).

**Comment by xiekevin** [comment]
Ah you're totally right, my apologies
